/**
 * Turn an AnalysisResult into a runnable, self-contained Vitest file.
 *
 * Design rules, each of which is enforced by a test:
 *   - The fixture is INLINED, never fetched. A regression test that phones an
 *     observability API for its own input is a liability — it must still pass in
 *     CI six months from now with no network and no credentials.
 *   - Tool responses replay from the recording, so the world stays fixed.
 *   - One finding → one it(), with the human-readable `detail` rendered as a
 *     comment above the assertion explaining why the test exists.
 */

import type { AnalysisResult, Assertion, Finding } from "./types";

function renderAssertion(a: Assertion): string {
  switch (a.kind) {
    case "passesToolResultToModel":
      return `expect(result).toPassToolResultToModel(${JSON.stringify(a.toolName)});`;
    case "onlyCallsDeclaredTools":
      return `expect(result).toOnlyCallDeclaredTools();`;
    case "callsToolAtMost":
      return `expect(result).toHaveCalledToolAtMost(${JSON.stringify(a.toolName)}, ${a.max});`;
    case "doesNotOscillate":
      // Oscillation reduces to: neither tool is called an unbounded number of
      // times in an alternating pattern. We pin each to a small bound.
      return (
        `expect(result).toHaveCalledToolAtMost(${JSON.stringify(a.toolA)}, 2);\n` +
        `    expect(result).toHaveCalledToolAtMost(${JSON.stringify(a.toolB)}, 2);`
      );
    case "toolSucceeds":
      return `expect(result).toHaveToolSucceeded(${JSON.stringify(a.toolName)});`;
    case "stepSucceeds":
      return `expect(result).toHaveSucceeded();`;
    case "runSucceeds":
      return `expect(result).toHaveSucceeded();`;
    case "nonEmptyResponse":
      return `expect(result).toHaveNonEmptyResponse();`;
    case "completeResponse":
      return `expect(result).toHaveCompleteResponse(${JSON.stringify(a.stepId)});`;
    case "callsTool":
      return `expect(result).toHaveCalledTool(${JSON.stringify(a.toolName)});`;
  }
}

function commentBlock(f: Finding): string {
  const lines = wrap(f.detail, 76);
  return lines.map((l) => `    // ${l}`).join("\n");
}

function wrap(text: string, width: number): string[] {
  const words = text.split(/\s+/);
  const out: string[] = [];
  let line = "";
  for (const w of words) {
    if ((line + " " + w).trim().length > width) {
      if (line) out.push(line);
      line = w;
    } else {
      line = (line + " " + w).trim();
    }
  }
  if (line) out.push(line);
  return out;
}

function testName(f: Finding): string {
  return `[${f.detector}] ${f.title}`.replace(/`/g, "'");
}

export function generateEval(analysis: AnalysisResult): string {
  const { trace, findings, silentCount } = analysis;
  // The recording is inlined verbatim. This is the whole hermeticity guarantee.
  const fixture = JSON.stringify(rebuildBundle(analysis), null, 2);

  const header = `// Regression test generated by Blackbox from run ${trace.runId}.
//
// ${findings.length} finding(s), ${silentCount} of them SILENT — invisible to
// status-code monitoring, because this run reported status_code ${trace.statusCode}.
//
// The trace is inlined below. This test is hermetic: no network, no
// credentials, no observability backend. It will pass or fail on its own in CI
// forever. Tool responses are replayed from the recording so the agent's world
// is held fixed and we assert only on its reasoning.

import { describe, it, expect } from "vitest";
import { replay } from "@blackbox/core/replay";
import "@blackbox/core/matchers";

const recording = ${fixture} as const;
`;

  const body = findings
    .map((f) => {
      return `  it(${JSON.stringify(testName(f))}, () => {
    const result = replay(recording as any);
${commentBlock(f)}
    ${renderAssertion(f.assertion)}
  });`;
    })
    .join("\n\n");

  return `${header}
describe("regression: run ${trace.runId}", () => {
${body}
});
`;
}

/**
 * Reconstruct the on-disk bundle shape from the analyzed trace so the generated
 * test replays exactly what was recorded.
 */
function rebuildBundle(analysis: AnalysisResult): unknown {
  const { trace } = analysis;
  return {
    type: "run",
    run_id: trace.runId,
    session_id: trace.sessionId,
    prompt: {
      user_prompt: trace.userPrompt,
      ...(trace.systemPrompt ? { system_prompt: trace.systemPrompt } : {}),
    },
    response: trace.response,
    start_time: new Date(trace.startTime).toISOString(),
    end_time: new Date(trace.endTime).toISOString(),
    status_code: trace.statusCode,
    ...(trace.statusMessage ? { status_message: trace.statusMessage } : {}),
    steps: trace.steps.map((s) => ({
      type: "step",
      run_id: trace.runId,
      step_id: s.id,
      prompt: s.prompt,
      response: s.response,
      start_time: new Date(s.startTime).toISOString(),
      end_time: new Date(s.endTime).toISOString(),
      status_code: s.statusCode,
      ...(s.statusMessage ? { status_message: s.statusMessage } : {}),
      ...(s.modelUsed ? { model_used: s.modelUsed } : {}),
      ...(s.finishReason ? { finish_reason: s.finishReason } : {}),
      ...(s.declaredTools.length
        ? { tool_definitions: JSON.stringify(s.declaredTools.map((n) => ({ name: n }))) }
        : {}),
    })),
    toolCalls: trace.toolCalls.map((tc) => ({
      type: "tool_call",
      run_id: trace.runId,
      tool_call_id: tc.id,
      tool_name: tc.name,
      start_time: new Date(tc.startTime).toISOString(),
      end_time: new Date(tc.endTime).toISOString(),
      status_code: tc.statusCode,
      ...(tc.statusMessage ? { status_message: tc.statusMessage } : {}),
      ...(tc.argsRaw !== undefined ? { args: tc.argsRaw } : {}),
      ...(tc.resultRaw !== undefined ? { result: tc.resultRaw } : {}),
    })),
  };
}
